import os
from typing import List, Dict, Any
from pydantic import BaseModel, Field

from langchain_community.document_loaders import TextLoader
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_openai import ChatOpenAI
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma


# 1. Output Schema Definition
class RAGResponse(BaseModel):
    answer: str = Field(description="The response generated by the model based on the retrieved context.")
    source_ids: List[str] = Field(description="List of source document identifiers or file paths used.")


class RAGPipeline:
    def __init__(self, source_path: str):
        # Local HuggingFace embeddings running on CPU
        self.embeddings = HuggingFaceEmbeddings(
            model_name="all-MiniLM-L6-v2"
        )

      # OpenRouter Chat Model setup using an active free slug
        self.llm = ChatOpenAI(
            model="openrouter/free",  # Active free model on OpenRouter
            openai_api_key=os.getenv("OPENAI_API_KEY"),
            openai_api_base=os.getenv("OPENAI_BASE_URL", "https://openrouter.ai/api/v1")
        )

        # Enforce structured output matching RAGResponse schema
        self.structured_llm = self.llm.with_structured_output(RAGResponse)

        # Load document context
        loader = TextLoader(source_path)
        docs = loader.load()

        # Split document into chunks
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=500,
            chunk_overlap=50
        )
        split_docs = text_splitter.split_documents(docs)

        # Initialize local Chroma vector database
        self.vectorstore = Chroma.from_documents(
            documents=split_docs,
            embedding=self.embeddings
        )

    def generate_answer(self, query: str, k: int = 3) -> Dict[str, Any]:
        """Retrieves relevant context chunks and generates a structured answer."""
        retriever = self.vectorstore.as_retriever(search_kwargs={"k": k})
        context_docs = retriever.invoke(query)

        # Combine text content from retrieved chunks
        context_text = "\n\n".join([doc.page_content for doc in context_docs])
        
        # Extract unique document source paths from metadata
        sources = list(set([doc.metadata.get("source", "app/document.txt") for doc in context_docs]))

        prompt = (
            f"Use the following context to answer the question:\n\n"
            f"Context:\n{context_text}\n\n"
            f"Question: {query}"
        )

        try:
            # Generate structured output using Pydantic schema
            result: RAGResponse = self.structured_llm.invoke(prompt)
            output = result.model_dump()

            # Ensure source_ids is populated
            if not output.get("source_ids"):
                output["source_ids"] = sources

            return output

        except Exception:
            # Fallback for models or API routing that fail native structured output
            raw_response = self.llm.invoke(prompt)
            return {
                "answer": str(raw_response.content),
                "source_ids": sources
            }

    # Backward compatibility alias
    query = generate_answer